name: world_explorer
description: "Explore countries with live weather, emergency contacts, and local infoâ€”all in one app."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.4+4

environment:
  sdk: ^3.7.0

dependencies:
    flutter:
      sdk: flutter
    flutter_localizations:
      sdk: flutter
    intl: ^0.20.2

    cupertino_icons: ^1.0.8
    http: ^1.1.0
    shared_preferences: ^2.2.2
    geolocator: ^14.0.0
    geolocator_web: ^4.0.0
    permission_handler: ^11.0.1
    firebase_core: ^2.0.0
    firebase_crashlytics: ^3.0.0
    flutter_riverpod: ^2.4.0
    dio: ^5.4.0
    hive: ^2.2.3
    hive_flutter: ^1.1.0
    path_provider: ^2.1.1
    json_annotation: ^4.8.1
    country_flags: ^2.0.1
    flutter_svg: ^2.0.7
    url_launcher: ^6.2.5
    vector_map: ^0.7.0
    countries_world_map: ^1.0.0
    flutter_map: ^6.1.0
    latlong2: ^0.9.1
    country_map_svg: ^0.0.4
    connectivity_plus: ^5.0.2
    smooth_page_indicator: ^1.1.0
    provider: ^6.1.0
    sqflite: ^2.3.2
    path: ^1.9.0
    flutter_dotenv: ^5.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^5.4.4
  build_runner: ^2.4.7
  test: ^1.24.9
  json_serializable: ^6.7.1
  change_app_package_name: ^1.5.0
  flutter_native_splash: ^2.3.5
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true


  assets:
    - .env
    - assets/
    - assets/weather/100/
    - assets/weather/200/
    - assets/emergency_data.json
    - assets/splash.png


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon/app_icon_round.png"
  remove_alpha_ios: true

flutter_native_splash:
  background_image: "assets/splash.png"
  android_gravity: fill
  android: true
  ios: true
  fullscreen: true


  #android_12:
   # image: assets/splash.png
   # image_dark: assets/splash.png
   # icon_background_color: null
   # icon_background_color_dark: null
